name = "mypaycheck-by-state"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[build]
command = ""
upload.format = "directory"

[functions]
directory = "functions"

[env.production]
name = "mypaycheck-by-state-prod"
