name = "mypaycheck-by-state"
compatibility_date = "2024-01-01"
main = "workers-site/index.js"

# Build output directory for Pages
pages_build_output_dir = "./public"

[build]
command = ""

[site]
bucket = "./public"
